// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjEscola.Data;

#nullable disable

namespace ProjEscola.Migrations
{
    [DbContext(typeof(ProjEscolaContext))]
    [Migration("20230116161622_AlteraDbProjProfessor01")]
    partial class AlteraDbProjProfessor01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjEscola.Models.ProjEstudante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataNascimentoEstudante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailEstudante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoneEstudante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEstudante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjEstudante");
                });

            modelBuilder.Entity("ProjEscola.Models.ProjProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificadosProfessor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisponibilidadeHorarioProfessor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailProfessor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProfessor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorHoraProfessor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProjProfessor");
                });

            modelBuilder.Entity("ProjEscola.Models.ProjTurma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeTurma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjTurma");
                });
#pragma warning restore 612, 618
        }
    }
}
